remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: "Dr. Christopher Steven Marcum's Personal Website"
#description: ""
logo: logos/profile72025.JPG
google_analytics: G-15ZDHCFDLG
